### PR TITLE
Feature task query

### PR DESCRIPTION
**Pull request by tguar**
Wanted to change the query from getting all tasks to getting tasks that are valid for today.

Tasks are valid if they satisfy one of the following:
1) computedWeight > userWeight. _this means that the user has deferred a previous day's task_
2) lastCompletedDt + repeatFloor == today's date.  _last completed + the repeat floor being today means that task should be worked_

My thinking is this query will return all the tasks then the api service will be in charge of implementing the business logic to sort the tasks for the client

### CODE REVIEW

**Comment by tguar** [comment]
I plan on adding a new route and endpoint to support this but if you pull now and run `GET {{baseURL}}/tasks/` you can should see the valid events.

To increase result size you can edit the db data to:
1) make computedWeight > userWeight

or

2) edit lastCompletedDt to be CURRENT DATE - repeatFloor e.g. if todays date was 2021/01/25 and repeatFloor was 2, edit lastCompletedDt to 2021/01/23

**Comment by jin0s** [comment]
we can add some query parameter to the existing GET /tasks/ route.
e.g. GET localhost:5000/tasks?for=today

Then in the controller it can handle which service to use:

```
if(req.query.param === 'today'){
  tasks.service.getTodaysTask
} else {
  tasks.service.getTasks // default to get all tasks
}
````

**Comment by tguar** [comment]
> we can add some query parameter to the existing GET /tasks/ route.
> e.g. GET localhost:5000/tasks?for=today
> 
> Then in the controller it can handle which service to use:
> 
> ```
> if(req.query.param === 'today'){
>   tasks.service.getTodaysTask
> } else {
>   tasks.service.getTasks // default to get all tasks
> }
> ```

I like this. For now `today` gets today and blank gets all

**Comment by jin0s** [comment]
I'm just thinking ahead. what are all the possible get requests that we can do?
- All
- By Id
- Today
- Next 5

It will be simpler to just keep it separate for now. So the current
localhost:5000/tasks/ will be broken up into:
- All,  GET: localhost:5000/tasks/
- By Id, GET: localhost:5000/tasks/id/:id
- Today, GET: localhost:5000/tasks/today
- Next 5, GET: localhost:5000/tasks/next?value=5

**Comment by tguar** [comment]
> I'm just thinking ahead. what are all the possible get requests that we can do?
> 
> * All
> * By Id
> * Today
> * Next 5
> 
> It will be simpler to just keep it separate for now. So the current
> localhost:5000/tasks/ will be broken up into:
> 
> * All,  GET: localhost:5000/tasks/
> * By Id, GET: localhost:5000/tasks/id/:id
> * Today, GET: localhost:5000/tasks/today
> * Next 5, GET: localhost:5000/tasks/next?value=5

We are going to axe next 5 for now I think, but if we want to add it later it would just be another param check

**Pull request merged**
